/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmsModal: typeof import('./src/components/ConfirmsModal.vue')['default']
    FlashMessageBox: typeof import('./src/components/FlashMessageBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
  }
}
